# Generated by Django 4.1 on 2022-08-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='owner',
            new_name='reviewer',
        ),
    ]
